### ISSUE TITLE
"New" button removes all objects from the 2D and 3D views. (Slicer 2020)

### ISSUE THREAD

**Issue by allemangD** [BICCN/cell-locator#135]
**Environment**

* OS: Ubuntu 20.04
* Revision: PR https://github.com/BICCN/cell-locator/pull/131

**Description**

Using the "New" button removes all objects from both the 2D and 3D views, making the app unusable. No prompt is given to select a location, and no error messages appear in the log.

**How to Reproduce**

1. Start the application
2. Click "New"
3. Select a location using the file dialog.

![image](https://user-images.githubusercontent.com/10702931/90930172-15631200-e3c8-11ea-8076-129aa43f1384.png)

**Comment by jcfr** [comment]
As of https://github.com/BICCN/cell-locator/commit/4104f2f58acf1ea2321ec747f360126faa325c77, clicking on `New` clear the scene put prevent the user from adding an other annotation.

The following is displayed:

```pytb
Traceback (most recent call last):
  File "/home/jcfr/Projects/cell-locator-RelWithDebInfo-build/Slicer-build/lib/CellLocator-4.11/qt-scripted-modules/Home.py", line 565, in onNewAnnotationButtonClicked
    self.setAnnotations(annotations)
  File "/home/jcfr/Projects/cell-locator-RelWithDebInfo-build/Slicer-build/lib/CellLocator-4.11/qt-scripted-modules/Home.py", line 491, in setAnnotations
    self.setInteractionState('explore')
  File "/home/jcfr/Projects/cell-locator-RelWithDebInfo-build/Slicer-build/lib/CellLocator-4.11/qt-scripted-modules/Home.py", line 1323, in setInteractionState
    selectionNode.SetActivePlaceNodeID(self.Annotations.current.markup.GetID())
AttributeError: 'NoneType' object has no attribute 'markup'
```

@allemangD  Could you have a look ?
